main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
