fos_user:
    resource: "@FOSUserBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /
